main: fr.peaceandcube.pacbirthday.PACBirthday
name: PACBirthday
description: A plugin allowing players to set and see their birthday
version: 1.4.0
author: YanisBft
website: https://github.com/PeaceAndCubeMC/PACBirthday
api-version: 1.13

depend: [pAcPI]

commands:
  setbirthday:
    description: Allows you to set your own birthday
    aliases: setbd
    permission: pacbirthday.set
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/setbirthday <day> <month>"
  birthday:
    description: Allows you to see a player's birthday
    aliases: bd
    permission: pacbirthday.see
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/birthday <player>"
  birthdays:
    description: Allows you to see the players having their birthday today
    permission: pacbirthday.today
    permission-message: §cYou do not have the permission to use this command.
    usage: "§eUsage: §r/birthdays"

permissions:
  pacbirthday.set:
    description: Allows you to set your own birthday
    default: true
  pacbirthday.see:
    description: Allows you to see a player's birthday
    default: true
  pacbirthday.today:
    description: Allows you to see the players having their birthday today
    default: true
